// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCSfgvW0tXc-SvDtE9nOg4R-MmCz7MnSo',
    appId: '1:883074652895:web:480f63f0f85df0e908e76a',
    messagingSenderId: '883074652895',
    projectId: 'trip-companion-5a2d2',
    authDomain: 'trip-companion-5a2d2.firebaseapp.com',
    storageBucket: 'trip-companion-5a2d2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbLNX-sVXZZxXmAj8f6WWCsfKNNgw6teQ',
    appId: '1:883074652895:android:5f46aaee338f5f3c08e76a',
    messagingSenderId: '883074652895',
    projectId: 'trip-companion-5a2d2',
    storageBucket: 'trip-companion-5a2d2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6hDizZR9SKgIcuActNXXQSfI8k-vELTI',
    appId: '1:883074652895:ios:94e19c40528ac85c08e76a',
    messagingSenderId: '883074652895',
    projectId: 'trip-companion-5a2d2',
    storageBucket: 'trip-companion-5a2d2.firebasestorage.app',
    iosBundleId: 'com.example.travelCompanion',
  );
}
